version: 2

sources:
  - name: jaffle_shop1     
    schema: jaffle_shop       
    database: raw_demo    
    tables:
      - name: stg_orders
        identifier: orders
        loaded_at_field: _ETL_LOADED_AT
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: stg_customers
        identifier: customers